export enum ACTIONS {
  SET_CHARACTER_ACTION = "SET_CHARACTER_ACTION",
  SET_SELECTED_CHARACTER_ACTION = "SET_SELECTED_CHARACTER_ACTION",
  SET_LOCATION_ACTION = "SET_LOCATION_ACTION",
  SET_SELECTED_LOCATION_ACTION = "SET_SELECTED_LOCATION_ACTION",
  SET_EPISODE_ACTION = "SET_EPISODE_ACTION",
  SET_SELECTED_EPISODE_ACTION = "SET_SELECTED_EPISODE_ACTION",
  SET_SERIAL_ERROR_ACTION = "SET_SERIAL_ERROR_ACTION",

  GET_CHARACTER_ACTION = "GET_CHARACTER_ACTION",
  GET_SELECTED_CHARACTER_ACTION = "GET_SELECTED_CHARACTER_ACTION",
  GET_LOCATION_ACTION = "GET_LOCATION_ACTION",
  GET_SELECTED_LOCATION_ACTION = "GET_SELECTED_LOCATION_ACTION",
  GET_EPISODE_ACTION = "GET_EPISODE_ACTION",
  GET_SELECTED_EPISODE_ACTION = "GET_SELECTED_EPISODE_ACTION",
  GET_SERIAL_ERROR_ACTION = "GET_SERIAL_ERROR_ACTION",

  SET_CURRENT_CHARACTER_PAGE_ACTION = "SET_CURRENT_CHARACTER_PAGE_ACTION",
  SET_CURRENT_LOCATION_PAGE_ACTION = "SET_CURRENT_LOCATION_PAGE_ACTION",
  SET_CURRENT_EPISODE_PAGE_ACTION = "SET_CURRENT_EPISODE_PAGE_ACTION",

  SET_MAIN_CHARACTER_ACTION = "SET_MAIN_CHARACTER_ACTION",
  GET_MAIN_CHARACTER_ACTION = "GET_MAIN_CHARACTER_ACTION",
}
