export enum ACTIONS {
  SET_CHARACTER_ACTION = "SET_CHARACTER_ACTION",
  SET_SELECTED_CHARACTER_ACTION = "SET_SELECTED_CHARACTER_ACTION",
  SET_LOCATION_ACTION = "SET_LOCATION_ACTION",
  SET_SELECTED_LOCATION_ACTION = "SET_SELECTED_LOCATION_ACTION",
  SET_EPISODE_ACTION = "SET_EPISODE_ACTION",
  SET_SELECTED_EPISODE_ACTION = "SET_SELECTED_EPISODE_ACTION",
  SET_SERIAL_ERROR_ACTION = "SET_SERIAL_ERROR_ACTION",
}
